### PR TITLE
refactor: drop lodash dependency

### LINKED ISSUE #19: drop lodash
Hi @nareshbhatia,

I wanted to try joinjs and noticed it carried a lodash dependency but used few of lodash's functions. While this lib is a few KB and 1 file, requiring lodash makes it 1.35MB and 1,053 files. It also has a very heavy and slow Babel build system. All of this seemed like extreme overkill to me, so I have forked this repo [1] and made a more streamlined version that still passes all tests, drops lodash, replaces Babel with Rollup & Buble and removes a bunch of other dev deps, greatly reducing dev install size.

Installed `npm i join-js` size of `node_modules`:

```
Before:      1.35 MB,    1,053 Files,    4 Folders
After:       8.05 KB,        1 Files,    1 Folder
```

Installed with devDependenices `node_modules` before & after:

node_modules

even if you're not on board with the devDeps changes, i encourage you to drop lodash from your deps, too.

cheers!

[1] https://github.com/leeoniya/joinjs

### PR DESCRIPTION
**Pull request by leeoniya**
fix #19

### CODE REVIEW

**Comment by nareshbhatia** [comment]
@leeoniya, build is failing due to lint errors. Can you please make sure lint runs error-free and then tests still run error free.

**Comment by leeoniya** [comment]
i could not get lint working either. but we'll see what travis says. tests pass.

**Comment by nareshbhatia** [comment]
Thanks @leeoniya for the fast turnaround!

**Pull request merged**
